version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: proje_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: proje_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword123
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: proje_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine
    container_name: proje_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  api-gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: proje_api
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql_db
      REDIS_HOST: redis
      GEMINI_API_KEY: AIzaSyDMkg7PwsTjb2hgjao8sJb03ZWun-rpEi8
    depends_on:
      mysql_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - uploads_data:/app/uploads
    restart: on-failure

  # --- CRUD WORKER ---
  crud-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    container_name: proje_crud_worker
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql_db
    depends_on:
      mysql_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  # --- LOG WORKER ---
  log-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.log_worker
    container_name: proje_log_worker
    environment:
      RABBITMQ_HOST: rabbitmq
      MYSQL_HOST: mysql_db
    depends_on:
      mysql_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  # --- FRONTEND ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proje_frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway

volumes:
  mysql_data:
  uploads_data: